[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "album-solution-api"
version = "0.7.2"
authors = [
    {name = "Jan Philipp Albrecht", email = "album@jpalbrecht.de"},
    {name = "Kyle Harrington", email = "album@kyleharrington.com"},
    {name = "Deborah Schmidt", email = "mail@frauzufall.de"}
]
maintainers = [
    {name = "Jan Philipp Albrecht", email = "album@jpalbrecht.de"},
    {name = "Kyle Harrington", email = "album@kyleharrington.com"},
    {name = "Deborah Schmidt", email = "mail@frauzufall.de"}
]
description = "Album is a framework for unifying computational tools across frameworks, languages, and environments."
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
keywords = ["virtual environments", "imaging", "data analysis"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Utilities"
]
requires-python = ">=3.6"

[project.urls]
Documentation = "https://docs.album.solutions/en/latest/"
Homepage = "https://album.solutions/"
DeveloperDocumentation = "https://gitlab.com/album-app/album/-/wikis/home"
Repository = "https://gitlab.com/album-app/album-solution-api"
Tracker= "https://gitlab.com/album-app/album-solution-api/issues"


[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ['*.json']
